// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SessionAssistant.API.Persistence;

#nullable disable

namespace SessionAssistant.API.Persistence.Migrations
{
    [DbContext(typeof(SessionAssistantReadDbContext))]
    [Migration("20241019160316_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("SessionAssistant.API.Persistence.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanDodge")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanParry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanDodge = true,
                            CanParry = true,
                            Name = "Gerlach Bauer"
                        },
                        new
                        {
                            Id = 2,
                            CanDodge = false,
                            CanParry = true,
                            Name = "Roborbor"
                        },
                        new
                        {
                            Id = 3,
                            CanDodge = false,
                            CanParry = false,
                            Name = "Pan Robak"
                        },
                        new
                        {
                            Id = 4,
                            CanDodge = true,
                            CanParry = true,
                            Name = "Chad Poggington"
                        });
                });

            modelBuilder.Entity("SessionAssistant.Shared.DTOs.Combat.CombatantDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attacks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanAct")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EncounterDTOId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Initiative")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EncounterDTOId");

                    b.ToTable("CombatantDTO");
                });

            modelBuilder.Entity("SessionAssistant.Shared.DTOs.Combat.EncounterDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Encounters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentRound = 1
                        },
                        new
                        {
                            Id = 2,
                            CurrentRound = 1
                        });
                });

            modelBuilder.Entity("SessionAssistant.Shared.DTOs.Combat.SkillDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CombatantDTOId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cooldown")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CombatantDTOId");

                    b.ToTable("SkillDTO");
                });

            modelBuilder.Entity("SessionAssistant.Shared.DTOs.Combat.CombatantDTO", b =>
                {
                    b.HasOne("SessionAssistant.Shared.DTOs.Combat.EncounterDTO", null)
                        .WithMany("Combatants")
                        .HasForeignKey("EncounterDTOId");
                });

            modelBuilder.Entity("SessionAssistant.Shared.DTOs.Combat.SkillDTO", b =>
                {
                    b.HasOne("SessionAssistant.Shared.DTOs.Combat.CombatantDTO", null)
                        .WithMany("Skills")
                        .HasForeignKey("CombatantDTOId");
                });

            modelBuilder.Entity("SessionAssistant.Shared.DTOs.Combat.CombatantDTO", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("SessionAssistant.Shared.DTOs.Combat.EncounterDTO", b =>
                {
                    b.Navigation("Combatants");
                });
#pragma warning restore 612, 618
        }
    }
}
