// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SessionAssistant.API.Persistence;

#nullable disable

namespace SessionAssistant.API.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241030211200_ReinitializedMigrations")]
    partial class ReinitializedMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("SessionAssistant.API.Persistence.Combatant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActPriority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attacks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EncounterId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCompletedRound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Initiative")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId");

                    b.ToTable("Combatants", (string)null);
                });

            modelBuilder.Entity("SessionAssistant.API.Persistence.Encounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActingInitiative")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActingPriority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Encounters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActingInitiative = 100,
                            ActingPriority = 0,
                            CurrentRound = 1
                        },
                        new
                        {
                            Id = 2,
                            ActingInitiative = 100,
                            ActingPriority = 0,
                            CurrentRound = 1
                        });
                });

            modelBuilder.Entity("SessionAssistant.API.Persistence.Combatant", b =>
                {
                    b.HasOne("SessionAssistant.API.Persistence.Encounter", null)
                        .WithMany("Combatants")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SessionAssistant.API.Persistence.Encounter", b =>
                {
                    b.Navigation("Combatants");
                });
#pragma warning restore 612, 618
        }
    }
}
